### ISSUE TITLE
frontend api endpoint need to be updated

### ISSUE THREAD

**Issue by yaolin902** [argus1/MyInspectionBuddy#20]
replace `http://10.0.0.63:5001` to `https://api.healthly.dev`

**Comment by argus1** [comment]
Is this repo-wide?

**Comment by yaolin902** [comment]
yes

**Comment by yaolin902** [comment]
fixed https://github.com/argus1/MyInspectionBuddy/commit/0b1b7069c40830000ac37a938531d9d418aa9d19
